
#设置tomcat服务端口号
server:
  port: 9000

#设置服务名称
spring:
  application:
    name: eureka-provider

eureka:
  client:
    #注册中心不需要注册自己
    register-with-eureka: true
    #注册中心不需要去发现服务
    fetch-registry: true
    serviceUrl:
      #设置服务注册中心的URL
      defaultZone: http://localhost:1111/eureka

# spring-boot-actuator 的端口
management:
  port: 11111

